version: '3'

services:
  db:
    build:
      context: ./db
    container_name: container_db
    volumes:
      - data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_ada
      POSTGRES_USER: user_ada
      POSTGRES_PASSWORD: password_ada
    networks:
      - ada_network

  app:
    build:
      context: ./app
    container_name: container_flask
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - ada_network

volumes:
  data_volume:

networks:
  ada_network:
    driver: bridge